# Generated by Django 5.0.6 on 2024-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.IntegerField()),
                ('blue', models.IntegerField(null=True)),
                ('clock_speed', models.FloatField(null=True)),
                ('dual_sim', models.IntegerField(null=True)),
                ('fc', models.IntegerField(null=True)),
                ('four_g', models.IntegerField(null=True)),
                ('int_memory', models.IntegerField(null=True)),
                ('m_dep', models.FloatField(null=True)),
                ('mobile_wt', models.IntegerField(null=True)),
                ('n_cores', models.IntegerField(null=True)),
                ('pc', models.IntegerField(null=True)),
                ('px_height', models.IntegerField(null=True)),
                ('px_width', models.IntegerField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('sc_h', models.IntegerField(null=True)),
                ('sc_w', models.IntegerField(null=True)),
                ('talk_time', models.IntegerField(null=True)),
                ('three_g', models.IntegerField(null=True)),
                ('touch_screen', models.IntegerField(null=True)),
                ('wifi', models.IntegerField(null=True)),
                ('price_range', models.IntegerField(null=True)),
            ],
        ),
    ]
